"""All-healthcare roster. Role tuples: (id, name, keywords, body_areas, tier[, focus])."""
from .taxonomy import make_umbrella as U

MED, SURG, WC, EM, MH = "Medical specialties", "Surgical & perioperative", "Women's & children's health", "Emergency & critical care", "Mental health"
NUR, PHA, DX, AH, DEN, PH, PAL, INT = ("Nursing & midwifery", "Pharmacy & medicines", "Diagnostics & laboratory", "Allied health & rehabilitation",
                                       "Dental & oral health", "Public health & evidence", "Palliative care & ethics", "Integrative (evidence-graded)")

CATALOG = [
    # ---------------------------------------------------------------- medical specialties (organ systems)
    U("neuro", "Neuro",
      ("brain", "neuro", "neurological", "nerve", "spinal", "cerebral", "stroke", "epilepsy", "seizure", "dementia", "alzheimer", "parkinson",
       "migraine", "neuropathy", "multiple sclerosis", "cognitive", "concussion", "tbi", "brain injury", "cord", "cranial", "headache"),
      ("brain", "spinal cord", "peripheral nerves", "cranial nerves", "neuromuscular junction", "autonomic nervous system", "optic pathway", "vestibular system", "skin (neurocutaneous)"),
      ("cardio", "psych", "immuno", "onco", "endo", "msk", "rehab", "emerg"),
      names={"physician": "Neurologist (neuro physician)", "surgeon": "Neurosurgeon", "physio": "Neuro-physiotherapist", "toxicologist": "Neurotoxicologist",
             "diagnostics": "Neuro-diagnostics specialist (neuroradiology / neurophysiology)", "dermato": "Neuro-dermatology liaison"},
      extras=(("opthal", "Neuro-ophthalmologist", ("vision", "optic", "visual", "papilledema", "diplopia", "nystagmus"), ("eye", "optic pathway"), "physician"),
              ("psychol", "Neuropsychologist", ("memory", "cognition", "cognitive", "attention", "executive", "behavior"), ("brain",), "psychosocial"),
              ("onco", "Neuro-oncologist", ("glioma", "glioblastoma", "tumor", "tumour", "metastasis", "meningioma"), ("brain", "spinal cord"), "physician"),
              ("immuno", "Neuro-immunologist", ("autoimmune", "demyelinating", "encephalitis", "multiple sclerosis", "myasthenia"), ("brain", "spinal cord", "neuromuscular junction"), "physician"),
              ("pain", "Neuropathic pain specialist", ("pain", "neuralgia", "neuropathic", "analgesic", "gabapentin"), ("peripheral nerves", "spinal cord"), "physician"),
              ("neurotology", "Neuro-otologist", ("vertigo", "dizziness", "hearing", "tinnitus", "vestibular"), ("vestibular system", "cranial nerves"), "physician"),
              ("sleep", "Sleep neurologist", ("sleep", "insomnia", "narcolepsy", "restless", "circadian"), ("brain",), "physician"),
              ("nurse", "Neuroscience clinical nurse specialist", ("stroke unit", "nursing", "neuro observations"), ("brain",), "nurse"))),
    U("cardio", "Cardio", ("heart", "cardiac", "cardiovascular", "hypertension", "arrhythmia", "atrial", "coronary", "myocardial", "blood pressure", "heart failure", "cholesterol", "statin"),
      ("heart", "coronary arteries", "aorta", "peripheral vessels"), ("neuro", "endo", "nephro", "pulmo", "vasc", "pharm"),
      names={"physician": "Cardiologist", "surgeon": "Cardiac surgeon", "physio": "Cardiac rehabilitation physiotherapist", "toxicologist": "Cardiotoxicologist",
             "diagnostics": "Cardiac imaging / ECG specialist", "dermato": None},
      extras=(("ep", "Electrophysiologist", ("arrhythmia", "ablation", "pacemaker", "fibrillation", "qt"), ("heart",), "physician"),
              ("intervention", "Interventional cardiologist", ("stent", "angioplasty", "pci", "catheter", "coronary"), ("coronary arteries",), "physician"),
              ("hf", "Heart-failure specialist nurse", ("heart failure", "diuretic", "fluid", "titration"), ("heart",), "advanced"),
              ("prevent", "Preventive cardiology lipid specialist", ("cholesterol", "lipid", "statin", "risk", "prevention"), ("heart", "peripheral vessels"), "physician"))),
    U("vasc", "Vascular", ("vascular", "artery", "vein", "aneurysm", "varicose", "thrombosis", "dvt", "claudication", "lymphoedema", "lymphedema", "carotid", "peripheral artery"),
      ("arteries", "veins", "lymphatic system"), ("cardio", "neuro", "endo", "haem"),
      facets=("physician", "surgeon", "physio", "diagnostics"),
      names={"physician": "Vascular medicine physician (angiologist)", "surgeon": "Vascular surgeon", "physio": "Vascular / lymphoedema therapist", "diagnostics": "Vascular ultrasound specialist"},
      extras=(("wound", "Vascular wound-care nurse", ("ulcer", "wound", "compression", "limb"), ("arteries", "veins"), "nurse"),)),
    U("onco", "Onco", ("cancer", "tumor", "tumour", "carcinoma", "metastasis", "chemotherapy", "radiotherapy", "oncology", "malignant", "lymphoma", "leukemia", "immunotherapy"),
      ("any organ", "lymphatic system", "bone marrow"), ("immuno", "neuro", "endo", "haem", "pall", "pharm", "dx"),
      names={"physician": "Medical oncologist", "surgeon": "Surgical oncologist", "physio": "Oncology rehabilitation physiotherapist", "toxicologist": "Oncology toxicologist",
             "diagnostics": "Oncologic imaging / pathology specialist", "dermato": "Onco-dermatology liaison"},
      extras=(("radonc", "Radiation oncologist", ("radiotherapy", "radiation", "brachytherapy", "dose"), ("any organ",), "physician"),
              ("nurse", "Oncology clinical nurse specialist", ("chemotherapy", "infusion", "neutropenia", "side effects"), ("any organ",), "nurse"),
              ("paed", "Paediatric oncologist", ("childhood cancer", "paediatric", "pediatric"), ("any organ",), "physician"),
              ("genetic", "Cancer geneticist", ("brca", "hereditary", "lynch", "germline"), ("any organ",), "physician"))),
    U("haem", "Haematology", ("blood", "anaemia", "anemia", "haemophilia", "hemophilia", "clotting", "coagulation", "sickle", "thalassemia", "transfusion", "platelet", "anticoagulant"),
      ("blood", "bone marrow", "spleen"), ("onco", "immuno", "vasc", "pharm"), facets=("physician", "toxicologist", "diagnostics"),
      names={"physician": "Haematologist", "toxicologist": "Haematotoxicologist", "diagnostics": "Haematology laboratory specialist"},
      extras=(("transplant", "Bone-marrow transplant physician", ("transplant", "stem cell", "graft versus host", "gvhd"), ("bone marrow",), "physician"),
              ("transfusion", "Transfusion medicine specialist", ("transfusion", "blood bank", "blood product"), ("blood",), "physician"))),
    U("immuno", "Immuno", ("immune", "autoimmune", "lupus", "allergy", "inflammation", "cytokine", "vaccine", "immunodeficiency", "antibody", "anaphylaxis", "vasculitis"),
      ("immune system", "joints", "skin"), ("neuro", "onco", "gastro", "msk", "derm"),
      names={"physician": "Clinical immunologist", "surgeon": "Transplant surgeon", "physio": "Immunology rehabilitation physiotherapist", "toxicologist": "Immunotoxicologist",
             "diagnostics": "Immunology laboratory diagnostics specialist", "dermato": "Immuno-dermatologist"},
      extras=(("allergy", "Allergist", ("allergy", "anaphylaxis", "food allergy", "hay fever", "urticaria"), ("immune system", "skin"), "physician"),)),
    U("endo", "Endo", ("diabetes", "thyroid", "insulin", "hormone", "metabolic", "obesity", "adrenal", "pituitary", "glucose", "endocrine", "osteoporosis", "hba1c", "testosterone"),
      ("pancreas", "thyroid", "adrenal glands", "pituitary"), ("cardio", "neuro", "nephro", "nutri", "pharm"),
      names={"physician": "Endocrinologist", "surgeon": "Endocrine surgeon", "physio": "Metabolic rehabilitation physiotherapist", "toxicologist": "Endocrine-disruptor toxicologist",
             "diagnostics": "Endocrine diagnostics specialist", "dermato": "Endocrine-dermatology liaison"},
      extras=(("dnurse", "Diabetes specialist nurse / educator", ("diabetes", "insulin", "glucose monitoring", "self-management", "cgm"), ("pancreas",), "advanced"),)),
    U("gastro", "Gastro", ("gut", "bowel", "liver", "colitis", "crohn", "reflux", "ibs", "celiac", "microbiome", "hepatic", "digestive", "hepatitis", "cirrhosis", "endoscopy"),
      ("esophagus", "stomach", "intestines", "liver", "pancreas"), ("immuno", "onco", "neuro", "nutri", "infect"),
      names={"physician": "Gastroenterologist", "surgeon": "GI surgeon", "physio": "Pelvic-floor / GI physiotherapist", "toxicologist": "Hepatotoxicologist",
             "diagnostics": "Endoscopy / GI diagnostics specialist", "dermato": "Gastro-dermatology liaison"},
      extras=(("hepat", "Hepatologist", ("liver", "hepatitis", "cirrhosis", "nafld", "transplant"), ("liver",), "physician"),)),
    U("pulmo", "Pulmo", ("lung", "asthma", "copd", "pneumonia", "respiratory", "breathing", "oxygen", "bronchi", "pulmonary", "apnea", "cough", "inhaler", "cystic fibrosis"),
      ("lungs", "airways", "pleura"), ("cardio", "immuno", "onco", "infect", "emerg"),
      names={"physician": "Pulmonologist", "surgeon": "Thoracic surgeon", "physio": "Respiratory physiotherapist", "toxicologist": "Inhalation toxicologist",
             "diagnostics": "Pulmonary function / imaging specialist", "dermato": None},
      extras=(("sleep", "Sleep medicine physician", ("sleep apnea", "cpap", "snoring", "sleep"), ("airways",), "physician"),
              ("rt", "Respiratory therapist", ("ventilator", "oxygen therapy", "airway clearance", "spirometry"), ("lungs",), "allied"))),
    U("nephro", "Nephro", ("kidney", "renal", "dialysis", "creatinine", "proteinuria", "nephritis", "ckd", "egfr"),
      ("kidneys", "ureters"), ("cardio", "endo", "uro", "pharm"),
      names={"physician": "Nephrologist", "surgeon": "Transplant / vascular-access surgeon", "physio": "Renal rehabilitation physiotherapist", "toxicologist": "Nephrotoxicologist",
             "diagnostics": "Renal diagnostics specialist", "dermato": None},
      extras=(("rnurse", "Renal / dialysis nurse", ("dialysis", "fistula", "peritoneal", "haemodialysis"), ("kidneys",), "nurse"),)),
    U("uro", "Uro", ("urinary", "bladder", "prostate", "incontinence", "kidney stone", "erectile", "urology", "urethra", "catheter", "male infertility", "vasectomy"),
      ("bladder", "prostate", "urethra", "genitals"), ("nephro", "onco", "obgyn", "neuro"), facets=("physician", "surgeon", "physio", "diagnostics"),
      names={"physician": "Urologist", "surgeon": "Urological surgeon", "physio": "Pelvic-health physiotherapist", "diagnostics": "Urodynamics / uro-imaging specialist"},
      extras=(("andro", "Andrologist / men's health physician", ("testosterone", "erectile", "infertility", "andrology"), ("genitals",), "physician"),)),
    U("derm", "Derm", ("skin", "rash", "eczema", "psoriasis", "acne", "melanoma", "dermatitis", "hair loss", "wart", "mole", "urticaria", "rosacea", "wound"),
      ("skin", "hair", "nails"), ("immuno", "onco", "infect", "pharm"), facets=("physician", "surgeon", "toxicologist", "diagnostics"),
      names={"physician": "Dermatologist", "surgeon": "Dermatologic / Mohs surgeon", "toxicologist": "Contact-dermatitis / dermato-toxicologist", "diagnostics": "Dermatopathologist"},
      extras=(("wound", "Tissue-viability / wound-care nurse specialist", ("wound", "pressure ulcer", "dressing", "burn", "scar"), ("skin",), "nurse"),
              ("paed", "Paediatric dermatologist", ("infant", "childhood eczema", "birthmark", "paediatric"), ("skin",), "physician"))),
    U("ophth", "Eye", ("eye", "vision", "glaucoma", "cataract", "retina", "macular", "myopia", "cornea", "uveitis", "blindness", "dry eye", "diplopia"),
      ("eye", "retina", "optic nerve"), ("neuro", "endo", "immuno", "allied"), facets=("physician", "surgeon", "toxicologist", "diagnostics"),
      names={"physician": "Ophthalmologist", "surgeon": "Ophthalmic surgeon", "toxicologist": "Ocular toxicologist", "diagnostics": "Ophthalmic imaging specialist (OCT / fundus)"},
      extras=(("opt", "Optometrist", ("refraction", "glasses", "contact lens", "optometry", "screening"), ("eye",), "allied"),
              ("ortho", "Orthoptist", ("squint", "strabismus", "amblyopia", "binocular"), ("eye",), "allied"))),
    U("ent", "ENT", ("ear", "nose", "throat", "sinus", "hearing", "tinnitus", "tonsil", "voice", "swallowing", "dysphagia", "vertigo", "otitis", "hoarseness", "head and neck"),
      ("ear", "nose", "throat", "larynx"), ("neuro", "onco", "pulmo", "allied", "rehab"), facets=("physician", "surgeon", "toxicologist", "diagnostics"),
      names={"physician": "Otolaryngologist (ENT physician)", "surgeon": "ENT / head-and-neck surgeon", "toxicologist": "Ototoxicologist", "diagnostics": "ENT diagnostics specialist (endoscopy / audiometry)"},
      extras=(("audio", "Audiologist", ("audiometry", "hearing aid", "cochlear", "tinnitus", "hearing loss"), ("ear",), "allied"),
              ("vest", "Vestibular physiotherapist", ("vertigo", "balance", "bppv", "dizziness"), ("ear",), "allied"))),
    U("msk", "Musculoskeletal", ("bone", "joint", "muscle", "fracture", "osteoporosis", "tendon", "spine", "orthopedic", "orthopaedic", "back pain", "arthritis", "rheumatoid", "gout", "knee", "hip", "shoulder", "acl", "ligament", "meniscus", "cruciate"),
      ("bones", "joints", "muscles", "spine"), ("neuro", "immuno", "endo", "sportsmed", "rehab", "pharm"),
      names={"physician": "Rheumatologist / musculoskeletal physician", "surgeon": "Orthopedic surgeon", "physio": "Musculoskeletal physiotherapist", "toxicologist": "Musculoskeletal toxicologist",
             "diagnostics": "Musculoskeletal imaging specialist", "dermato": "Rheumato-dermatology liaison"},
      extras=(("spine", "Spine surgeon", ("spinal fusion", "disc", "stenosis", "scoliosis", "sciatica"), ("spine",), "surgeon"),
              ("fcp", "First-contact musculoskeletal practitioner (extended-scope physiotherapist)", ("triage", "injection", "first contact", "advanced practice"), ("joints", "spine"), "allied"),
              ("podo", "Podiatrist", ("foot", "ankle", "diabetic foot", "orthotic", "nail"), ("feet",), "allied"),
              ("ot", "Hand therapist / occupational therapist", ("hand", "splint", "wrist", "dexterity"), ("hands",), "allied"))),
    U("infect", "Infectious disease", ("infection", "antibiotic", "virus", "bacteria", "sepsis", "hiv", "tuberculosis", "malaria", "covid", "influenza", "fungal", "antimicrobial", "vaccination", "travel"),
      ("any organ", "blood", "lungs"), ("immuno", "pulmo", "pubh", "pharm", "dx"), facets=("physician", "toxicologist", "diagnostics"),
      names={"physician": "Infectious-disease physician", "toxicologist": "Antimicrobial / drug-resistance toxicologist", "diagnostics": "Infection diagnostics specialist"},
      extras=(("micro", "Clinical microbiologist", ("culture", "sensitivity", "pcr", "resistance", "stewardship"), ("any organ",), "diagnostic"),
              ("ipc", "Infection prevention & control nurse", ("hand hygiene", "outbreak", "isolation", "ppe"), ("any organ",), "nurse"),
              ("travel", "Travel medicine physician", ("travel", "malaria prophylaxis", "yellow fever"), ("any organ",), "physician"),
              ("sti", "Sexual-health physician", ("sexual health", "sti", "std", "chlamydia", "syphilis", "hiv prevention", "prep"), ("genitals",), "physician"))),
    U("geri", "Geriatric", ("elderly", "older adult", "ageing", "aging", "frailty", "falls", "polypharmacy", "delirium", "dementia care", "osteopenia", "nursing home", "sarcopenia"),
      ("whole body",), ("neuro", "cardio", "msk", "pharm", "pall", "psych"), facets=("physician", "physio", "toxicologist", "diagnostics"),
      names={"physician": "Geriatrician", "physio": "Falls / frailty physiotherapist", "toxicologist": "Polypharmacy toxicologist", "diagnostics": "Comprehensive geriatric assessment specialist"},
      extras=(("ortho", "Orthogeriatric physician", ("hip fracture", "fragility", "orthogeriatric"), ("bones",), "physician"),
              ("gnurse", "Gerontological nurse practitioner", ("care home", "advance care", "chronic disease", "elderly"), ("whole body",), "advanced"))),
    U("genetics", "Genetics", ("genetic", "gene", "genome", "hereditary", "mutation", "inherited", "brca", "pharmacogenomic", "chromosome", "carrier", "newborn screening", "rare disease"),
      ("dna",), ("onco", "paeds", "neuro", "pharm", "obgyn"), cat=MED, support=True, facets=(),
      extras=(("clin", "Clinical geneticist", ("genetic", "syndrome", "inherited", "rare disease", "chromosome"), ("dna",), "physician"),
              ("counsel", "Genetic counsellor", ("counselling", "risk", "family history", "carrier", "inheritance"), ("dna",), "advanced"),
              ("pgx", "Pharmacogenomics specialist", ("pharmacogenomic", "cyp2d6", "cyp2c19", "metabolizer", "hla"), ("dna",), "scientist"),
              ("metab", "Inherited metabolic disease physician", ("metabolic disorder", "enzyme", "newborn screening", "pku"), ("liver", "blood"), "physician"))),

    # ---------------------------------------------------------------- surgery & perioperative
    U("surgery", "General surgery", ("surgery", "surgical", "hernia", "appendix", "gallbladder", "colorectal", "bariatric", "breast", "burns", "transplant", "plastic", "reconstructive", "laparoscopic", "operation"),
      ("abdomen", "breast", "skin"), ("anaesth", "gastro", "onco", "nursing", "rehab"), cat=SURG, facets=(),
      extras=(("general", "General surgeon", ("hernia", "appendectomy", "cholecystectomy", "laparoscopic", "abdominal"), ("abdomen",), "surgeon"),
              ("colorectal", "Colorectal surgeon", ("colon", "rectal", "stoma", "haemorrhoid", "anal", "bowel resection"), ("intestines",), "surgeon"),
              ("hpb", "Hepato-pancreato-biliary surgeon", ("liver resection", "pancreatic", "whipple", "biliary"), ("liver", "pancreas"), "surgeon"),
              ("bariatric", "Bariatric surgeon", ("bariatric", "gastric bypass", "sleeve", "obesity surgery"), ("stomach",), "surgeon"),
              ("plastic", "Plastic & reconstructive surgeon", ("reconstruction", "flap", "burn", "cosmetic", "cleft", "scar"), ("skin",), "surgeon"),
              ("breast", "Breast surgeon", ("breast", "mastectomy", "lumpectomy", "reconstruction"), ("breast",), "surgeon"),
              ("transplant", "Transplant surgeon", ("transplant", "donor", "rejection", "immunosuppression"), ("any organ",), "surgeon"),
              ("assist", "Surgical care practitioner / physician associate (surgery)", ("first assistant", "pre-assessment", "wound closure", "surgical ward"), ("abdomen",), "advanced"),
              ("theatre", "Perioperative (theatre) nurse", ("theatre", "scrub", "sterile", "instrument count", "wound"), ("abdomen",), "nurse"),
              ("enhanced", "Enhanced-recovery (ERAS) specialist", ("enhanced recovery", "eras", "prehabilitation", "postoperative recovery"), ("whole body",), "advanced"))),
    U("anaesth", "Anaesthesia & pain", ("anaesthesia", "anesthesia", "anaesthetic", "sedation", "nerve block", "epidural", "chronic pain", "perioperative", "analgesia", "opioid", "pain management"),
      ("whole body", "spine", "nerves"), ("surgery", "emerg", "pharm", "neuro", "nursing"), cat=SURG, facets=(),
      extras=(("anaes", "Anaesthesiologist", ("general anaesthesia", "airway", "perioperative", "sedation", "preoperative assessment"), ("airways",), "physician"),
              ("regional", "Regional anaesthesia specialist", ("nerve block", "epidural", "spinal anaesthesia", "ultrasound-guided"), ("nerves", "spine"), "physician"),
              ("pain", "Pain medicine physician", ("chronic pain", "opioid", "pain management", "neuromodulation", "complex regional"), ("nerves", "spine"), "physician"),
              ("paintherapy", "Pain physiotherapist / pain psychologist", ("pain education", "graded exposure", "pacing", "cbt for pain"), ("whole body",), "allied"),
              ("odp", "Anaesthetic practitioner / operating-department practitioner", ("anaesthetic assistant", "airway equipment", "theatre"), ("airways",), "nurse"),
              ("perfus", "Clinical perfusionist", ("bypass", "ecmo", "perfusion", "cardiopulmonary"), ("heart",), "allied"))),

    # ---------------------------------------------------------------- women's & children's health
    U("obgyn", "Women's health", ("pregnancy", "pregnant", "obstetric", "gestational", "antenatal", "prenatal", "trimester", "caesarean", "gynaecology", "gynecology", "menopause", "fertility", "ivf", "contraception", "labour", "labor", "postpartum", "gestational", "antenatal", "prenatal", "trimester", "caesarean", "delivery", "endometriosis", "pcos", "cervical", "preeclampsia", "miscarriage"),
      ("uterus", "ovaries", "breast", "placenta"), ("endo", "paeds", "onco", "psych", "pharm", "genetics"), cat=WC, facets=("physician", "surgeon", "physio", "toxicologist", "diagnostics"),
      names={"physician": "Obstetrician-gynaecologist", "surgeon": "Gynaecological surgeon", "physio": "Women's / pelvic-health physiotherapist", "toxicologist": "Reproductive toxicologist / teratology specialist",
             "diagnostics": "Obstetric ultrasound / fetal imaging specialist"},
      extras=(("mfm", "Maternal-fetal medicine specialist", ("high-risk pregnancy", "preeclampsia", "fetal growth", "gestational diabetes"), ("uterus", "placenta"), "physician"),
              ("rei", "Reproductive endocrinologist / fertility specialist", ("ivf", "infertility", "ovulation", "fertility"), ("ovaries", "uterus"), "physician"),
              ("midwife", "Midwife", ("antenatal", "labour", "birth", "breastfeeding", "postnatal"), ("uterus",), "nurse"),
              ("meno", "Menopause specialist", ("menopause", "hrt", "hot flushes", "perimenopause"), ("ovaries",), "physician"),
              ("pnpsych", "Perinatal mental-health specialist", ("postnatal depression", "perinatal", "postpartum psychosis"), ("brain",), "physician"))),
    U("paeds", "Child health", ("child", "children", "paediatric", "pediatric", "infant", "baby", "newborn", "neonatal", "adolescent", "toddler", "growth", "congenital", "developmental", "autism", "vaccination schedule"),
      ("whole body",), ("neuro", "psych", "genetics", "nutri", "pharm", "immuno"), cat=WC,
      names={"physician": "Paediatrician", "surgeon": "Paediatric surgeon", "physio": "Paediatric physiotherapist", "toxicologist": "Paediatric toxicologist",
             "diagnostics": "Paediatric diagnostics / imaging specialist", "dermato": "Paediatric dermatology liaison"},
      extras=(("neonatal", "Neonatologist", ("premature", "preterm", "nicu", "neonatal", "newborn"), ("whole body",), "physician"),
              ("devpaed", "Developmental paediatrician", ("autism", "adhd", "developmental delay", "milestones", "learning disability"), ("brain",), "physician"),
              ("adolescent", "Adolescent medicine physician", ("adolescent", "puberty", "eating disorder", "teenager"), ("whole body",), "physician"),
              ("hv", "Health visitor / community children's nurse", ("health visitor", "school nurse", "immunisation", "child development"), ("whole body",), "nurse"),
              ("cpsych", "Child & adolescent psychologist", ("child behaviour", "anxiety in children", "parenting"), ("brain",), "psychosocial"))),

    # ---------------------------------------------------------------- emergency & critical care
    U("emerg", "Emergency & critical care", ("emergency", "trauma", "resuscitation", "cardiac arrest", "shock", "icu", "intensive care", "ventilator", "overdose", "poisoning", "burn", "triage", "major incident", "sepsis", "ambulance", "paramedic"),
      ("whole body",), ("surgery", "anaesth", "cardio", "pulmo", "pharm", "neuro"), cat=EM, facets=(),
      extras=(("em", "Emergency physician", ("emergency", "triage", "acute", "chest pain", "resuscitation"), ("whole body",), "acute"),
              ("icu", "Intensivist (critical-care physician)", ("icu", "ventilator", "vasopressor", "organ failure", "sepsis", "ards"), ("whole body",), "acute"),
              ("trauma", "Trauma surgeon", ("trauma", "haemorrhage", "damage control", "fracture", "penetrating"), ("whole body",), "surgeon"),
              ("para", "Paramedic / prehospital emergency practitioner", ("prehospital", "ambulance", "paramedic", "scene", "als"), ("whole body",), "acute"),
              ("enp", "Emergency nurse practitioner", ("minor injuries", "urgent care", "wound", "triage"), ("whole body",), "advanced"),
              ("icun", "Critical-care nurse", ("icu nursing", "ventilated", "sedation scoring", "delirium"), ("whole body",), "nurse"),
              ("tox", "Clinical toxicologist (poison centre)", ("overdose", "poisoning", "antidote", "paracetamol", "toxidrome", "envenomation"), ("whole body",), "scientist"),
              ("disaster", "Disaster / retrieval medicine specialist", ("disaster", "mass casualty", "retrieval", "aeromedical"), ("whole body",), "acute"))),

    # ---------------------------------------------------------------- mental health
    U("psych", "Psych", ("depression", "anxiety", "psychiatric", "schizophrenia", "bipolar", "adhd", "autism", "ptsd", "mood", "psychosis", "suicide", "self-harm", "eating disorder", "ocd", "addiction", "substance use", "alcohol", "mental health"),
      ("brain", "behavior"), ("neuro", "endo", "pharm", "paeds", "geri"), cat=MH,
      names={"physician": "Psychiatrist", "surgeon": "Neuromodulation / functional neurosurgeon", "physio": "Psychomotor therapist", "toxicologist": "Psychopharmacology toxicologist",
             "diagnostics": "Psychiatric assessment specialist", "dermato": "Psychodermatology liaison"},
      extras=(("psychologist", "Clinical psychologist", ("psychotherapy", "cbt", "therapy", "trauma", "assessment"), ("brain",), "psychosocial"),
              ("addiction", "Addiction medicine specialist", ("addiction", "substance use", "alcohol", "opioid dependence", "withdrawal", "detox"), ("brain",), "physician"),
              ("cap", "Child & adolescent psychiatrist", ("child", "adolescent", "adhd", "autism", "conduct"), ("brain",), "physician"),
              ("pnurse", "Mental-health nurse / nurse prescriber", ("crisis", "community mental health", "medication monitoring", "risk assessment"), ("brain",), "advanced"),
              ("counsellor", "Counsellor / psychotherapist", ("counselling", "grief", "relationship", "supportive therapy"), ("brain",), "psychosocial"),
              ("sw", "Mental-health social worker", ("social work", "housing", "safeguarding", "benefits", "carers"), ("whole body",), "psychosocial"),
              ("neuropsy", "Neuropsychiatrist", ("neuropsychiatry", "functional neurological", "organic psychosis", "catatonia"), ("brain",), "physician"))),

    # ---------------------------------------------------------------- nursing & midwifery
    U("nursing", "Nursing", ("nurse", "nursing", "ward", "care plan", "pressure ulcer", "observations", "catheter care", "discharge", "patient education", "community nursing", "district nurse", "falls prevention", "nurse practitioner", "advanced practice"),
      ("whole body",), ("pharm", "rehab", "geri", "emerg", "pall"), cat=NUR, support=True, facets=(),
      extras=(("np", "Nurse practitioner (advanced practice)", ("nurse practitioner", "prescribing", "advanced practice", "primary care", "chronic disease"), ("whole body",), "advanced"),
              ("pa", "Physician associate / advanced clinical practitioner", ("physician associate", "advanced clinical practitioner", "triage", "ward round"), ("whole body",), "advanced"),
              ("cns", "Clinical nurse specialist", ("specialist nurse", "clinic", "case management", "long-term condition"), ("whole body",), "nurse"),
              ("comm", "District / community nurse", ("district nurse", "home care", "wound care", "palliative at home", "community"), ("whole body",), "nurse"),
              ("tv", "Tissue-viability nurse", ("pressure ulcer", "wound", "dressing", "compression"), ("skin",), "nurse"),
              ("mh", "Mental-health nurse", ("mental health nursing", "observation", "crisis plan"), ("brain",), "nurse"),
              ("school", "School / occupational-health nurse", ("school nurse", "occupational health", "return to work", "screening"), ("whole body",), "nurse"),
              ("care", "Care coordinator / case manager", ("care coordination", "discharge planning", "integrated care", "case management"), ("whole body",), "nurse"),
              ("hca", "Healthcare assistant / nursing associate", ("basic care", "observations", "mobility assistance"), ("whole body",), "nurse"))),

    # ---------------------------------------------------------------- pharmacy & medicines
    U("pharm", "Pharmacy", ("drug", "medication", "medicine", "dose", "dosing", "interaction", "side effect", "adverse effect", "prescribing", "pharmacist", "polypharmacy", "deprescribing", "antidote", "generic", "formulary", "contraindication", "adherence"),
      ("whole body",), ("nursing", "geri", "psych", "infect", "emerg"), cat=PHA, support=True, facets=(),
      extras=(("clinical", "Clinical pharmacist", ("medication review", "interaction", "renal dosing", "adverse effect", "reconciliation"), ("whole body",), "pharmacist"),
              ("prescriber", "Pharmacist independent prescriber", ("prescribing", "minor ailment", "chronic disease clinic", "deprescribing", "vaccination"), ("whole body",), "pharmacist"),
              ("community", "Community pharmacist", ("over the counter", "dispensing", "minor ailment", "adherence", "inhaler technique"), ("whole body",), "pharmacist"),
              ("pharmacologist", "Clinical pharmacologist", ("pharmacokinetics", "pharmacodynamics", "mechanism", "dose response", "drug development"), ("whole body",), "scientist"),
              ("pgx", "Pharmacogenomics pharmacist", ("pharmacogenomic", "cyp", "genotype-guided"), ("dna",), "pharmacist"),
              ("tdm", "Therapeutic drug monitoring specialist", ("drug levels", "trough", "vancomycin", "lithium", "tdm"), ("blood",), "scientist"),
              ("mgmt", "Medicines-safety / pharmacovigilance specialist", ("pharmacovigilance", "adverse event", "yellow card", "recall", "medication error"), ("whole body",), "scientist"))),

    # ---------------------------------------------------------------- diagnostics & laboratory
    U("dx", "Diagnostics", ("radiology", "x-ray", "mri", "ct scan", "ultrasound", "pathology", "biopsy", "blood test", "laboratory", "lab", "biomarker", "pet", "histology", "screening", "diagnostic accuracy", "sensitivity", "specificity", "nuclear medicine"),
      ("whole body",), ("onco", "infect", "pharm"), cat=DX, support=True, facets=(),
      extras=(("rad", "Radiologist", ("x-ray", "ct", "mri", "ultrasound", "imaging", "radiology"), ("whole body",), "diagnostic"),
              ("ir", "Interventional radiologist", ("embolisation", "image-guided", "biopsy", "stent", "ablation"), ("whole body",), "diagnostic"),
              ("nm", "Nuclear medicine physician", ("pet", "spect", "radiotracer", "scintigraphy", "radionuclide"), ("whole body",), "diagnostic"),
              ("path", "Histopathologist / pathologist", ("histology", "biopsy", "cytology", "frozen section", "tumour grade"), ("whole body",), "diagnostic"),
              ("biochem", "Clinical biochemist", ("blood test", "reference range", "tumour marker", "troponin", "hba1c", "electrolytes"), ("blood",), "diagnostic"),
              ("molecular", "Molecular diagnostics scientist", ("pcr", "sequencing", "liquid biopsy", "genotyping"), ("dna",), "diagnostic"),
              ("radiographer", "Radiographer / sonographer", ("scan technique", "radiation dose", "positioning", "sonography"), ("whole body",), "allied"),
              ("physicist", "Medical physicist", ("radiation dose", "dosimetry", "image quality", "mri safety"), ("whole body",), "scientist"),
              ("ai", "Clinical AI / decision-support specialist", ("artificial intelligence", "machine learning", "algorithm", "decision support", "validation"), ("whole body",), "public"))),

    # ---------------------------------------------------------------- allied health & rehabilitation
    U("rehab", "Rehabilitation", ("rehabilitation", "physiotherapy", "occupational therapy", "speech therapy", "prosthesis", "amputation", "disability", "mobility", "activities of daily living", "return to work", "swallowing", "aphasia", "wheelchair"),
      ("whole body",), ("neuro", "msk", "ent", "nursing", "psych"), cat=AH, support=True, facets=(),
      extras=(("physiatrist", "Rehabilitation medicine physician (physiatrist)", ("rehabilitation", "spasticity", "disability", "botulinum", "functional recovery"), ("whole body",), "physician"),
              ("physio", "Physiotherapist", ("physiotherapy", "exercise", "mobility", "gait", "strength", "balance"), ("muscles", "joints"), "allied"),
              ("ot", "Occupational therapist", ("activities of daily living", "home adaptation", "cognitive rehab", "return to work", "equipment"), ("whole body",), "allied"),
              ("slt", "Speech & language therapist", ("speech", "language", "aphasia", "dysphagia", "swallowing", "voice", "stammer"), ("throat", "brain"), "allied"),
              ("po", "Prosthetist / orthotist", ("prosthesis", "orthosis", "amputation", "brace", "splint"), ("limbs",), "allied"),
              ("vr", "Vocational rehabilitation specialist", ("return to work", "workplace adjustment", "vocational"), ("whole body",), "allied"),
              ("recr", "Therapeutic recreation / music / art therapist", ("music therapy", "art therapy", "recreation", "creative"), ("brain",), "allied"))),
    U("allied", "Allied health", ("podiatry", "optometry", "dietetics", "osteopathy", "chiropractic", "orthoptics", "audiology", "exercise physiology", "respiratory therapy", "paramedicine"),
      ("whole body",), ("rehab", "nutri", "sportsmed", "msk"), cat=AH, support=True, facets=(),
      extras=(("podiatrist", "Podiatrist", ("foot", "ankle", "diabetic foot", "orthotic", "nail", "ulcer"), ("feet",), "allied"),
              ("exphys", "Accredited exercise physiologist", ("exercise prescription", "chronic disease exercise", "cardiac rehab", "vo2"), ("whole body",), "allied"),
              ("osteo", "Osteopath / chiropractor (manual therapy)", ("manual therapy", "spinal manipulation", "back pain", "neck pain", "mobilisation"), ("spine",), "allied"),
              ("aud", "Audiologist", ("hearing", "hearing aid", "audiometry", "tinnitus", "cochlear"), ("ear",), "allied"),
              ("chw", "Community health worker / health coach", ("health coaching", "self-management", "lifestyle", "community outreach", "navigation"), ("whole body",), "allied"),
              ("sw", "Medical social worker", ("social care", "discharge", "safeguarding", "housing", "carers"), ("whole body",), "psychosocial"))),
    U("nutri", "Nutrition", ("diet", "nutrition", "nutritional", "malnutrition", "weight loss", "calorie", "vitamin", "supplement", "enteral", "parenteral", "food allergy", "intolerance", "fasting", "mediterranean", "obesity", "bmi"),
      ("gut", "whole body"), ("endo", "gastro", "paeds", "pharm", "sportsmed"), cat=AH, support=True, facets=(),
      extras=(("rd", "Registered dietitian", ("diet", "dietary advice", "malnutrition", "medical nutrition therapy", "weight management"), ("gut",), "allied"),
              ("support", "Clinical nutrition support specialist (enteral / parenteral)", ("enteral", "parenteral", "tube feeding", "refeeding", "tpn"), ("gut",), "allied"),
              ("obesity", "Obesity medicine physician", ("obesity", "glp-1", "weight loss", "anti-obesity", "bmi"), ("whole body",), "physician"),
              ("peds", "Paediatric dietitian", ("infant feeding", "weaning", "faltering growth", "food allergy"), ("gut",), "allied"),
              ("sports", "Sports dietitian", ("sports nutrition", "protein", "hydration", "energy availability"), ("whole body",), "allied"))),
    U("sportsmed", "Sports & exercise", ("sport", "athlete", "exercise", "training", "overuse", "sprain", "strain", "concussion in sport", "return to play", "performance", "doping", "marathon"),
      ("muscles", "joints"), ("msk", "neuro", "cardio", "nutri", "rehab"), cat=MED, support=True, facets=(),
      extras=(("sp", "Sport & exercise medicine physician", ("return to play", "overuse injury", "athlete", "sports injury"), ("muscles", "joints"), "physician"),
              ("spt", "Sports physiotherapist", ("rehabilitation", "return to sport", "load management", "taping"), ("muscles", "joints"), "allied"),
              ("at", "Athletic trainer", ("on-field", "strapping", "prevention", "injury surveillance"), ("muscles",), "allied"),
              ("ep", "Exercise physiologist / strength & conditioning scientist", ("training load", "vo2", "periodisation", "strength"), ("whole body",), "scientist"),
              ("spsych", "Sport psychologist", ("performance anxiety", "motivation", "injury psychology"), ("brain",), "psychosocial"),
              ("anti", "Anti-doping / sports pharmacist", ("doping", "wada", "supplement", "banned substance"), ("whole body",), "pharmacist"))),

    # ---------------------------------------------------------------- dental & oral
    U("dental", "Dental", ("tooth", "teeth", "dental", "gum", "periodontal", "caries", "cavity", "orthodontic", "braces", "dentist", "oral", "mouth", "jaw", "implant", "root canal", "wisdom"),
      ("teeth", "gums", "jaw", "oral mucosa"), ("ent", "pharm", "paeds", "onco", "msk", "dx"), cat=DEN, facets=(),
      extras=(("gdp", "General dentist", ("caries", "filling", "extraction", "check-up", "prevention"), ("teeth",), "dental"),
              ("perio", "Periodontist", ("gum disease", "periodontitis", "gingivitis", "scaling", "bone loss"), ("gums",), "dental"),
              ("endo", "Endodontist", ("root canal", "pulpitis", "abscess", "apicectomy"), ("teeth",), "dental"),
              ("ortho", "Orthodontist", ("braces", "aligner", "malocclusion", "orthodontic"), ("teeth", "jaw"), "dental"),
              ("pros", "Prosthodontist", ("implant", "denture", "crown", "bridge", "veneer"), ("teeth",), "dental"),
              ("paed", "Paediatric dentist", ("child teeth", "fluoride", "sealant", "baby teeth"), ("teeth",), "dental"),
              ("omfs", "Oral & maxillofacial surgeon", ("jaw surgery", "wisdom tooth", "facial trauma", "oral cancer", "implant surgery", "tmj"), ("jaw",), "surgeon"),
              ("om", "Oral medicine specialist", ("oral ulcer", "lichen planus", "burning mouth", "oral lesion", "dry mouth"), ("oral mucosa",), "physician"),
              ("hyg", "Dental hygienist / therapist", ("scale and polish", "oral hygiene", "fluoride varnish", "dental therapy"), ("teeth", "gums"), "dental"),
              ("dpath", "Oral pathologist / dental radiologist", ("oral biopsy", "panoramic", "cbct", "oral pathology"), ("jaw",), "diagnostic"))),

    # ---------------------------------------------------------------- public health & evidence
    U("pubh", "Public health", ("population", "epidemiology", "prevention", "screening programme", "incidence", "prevalence", "risk factor", "outbreak", "vaccination programme", "health policy", "occupational", "environmental", "cohort", "randomised", "randomized", "meta-analysis", "bias", "confounding", "statistics", "cost-effective", "guideline", "health inequality", "evidence"),
      ("population",), ("infect", "dx", "pharm", "nutri"), cat=PH, support=True, facets=(),
      extras=(("phys", "Public-health physician", ("prevention", "screening programme", "health protection", "population health"), ("population",), "public"),
              ("epi", "Epidemiologist", ("incidence", "prevalence", "cohort", "case-control", "risk factor", "confounding"), ("population",), "public"),
              ("stats", "Biostatistician / evidence-based-medicine methodologist", ("meta-analysis", "randomised", "randomized", "bias", "confidence interval", "grade", "systematic review", "p-value", "effect size"), ("population",), "public"),
              ("occenv", "Occupational & environmental health physician", ("occupational", "workplace", "air pollution", "exposure limit", "asbestos", "noise"), ("population",), "public"),
              ("hta", "Health economist / HTA analyst", ("cost-effective", "qaly", "budget impact", "health technology assessment"), ("population",), "public"),
              ("vax", "Vaccinologist / immunisation programme lead", ("vaccine safety", "immunisation programme", "herd immunity", "coverage"), ("population",), "public"),
              ("informatics", "Health informatics / digital-health specialist", ("electronic health record", "digital health", "telehealth", "interoperability", "data quality"), ("population",), "public"),
              ("global", "Global-health specialist", ("low-income", "global health", "neglected disease", "humanitarian", "health systems"), ("population",), "public"),
              ("ipc", "Health-protection / infection-control specialist", ("surveillance", "contact tracing", "outbreak", "quarantine"), ("population",), "public"))),

    # ---------------------------------------------------------------- palliative care & ethics
    U("pall", "Palliative care", ("palliative", "end of life", "hospice", "dying", "advance care plan", "terminal", "symptom control", "bereavement", "dnr", "assisted dying", "capacity", "consent", "ethics", "ethical", "withdrawal of treatment"),
      ("whole body",), ("onco", "geri", "nursing", "psych", "pharm"), cat=PAL, support=True, facets=(),
      extras=(("phys", "Palliative-medicine physician", ("palliative", "symptom control", "end of life", "syringe driver", "breathlessness"), ("whole body",), "physician"),
              ("nurse", "Hospice / palliative clinical nurse specialist", ("hospice", "home care", "dying", "comfort", "anticipatory"), ("whole body",), "nurse"),
              ("ethics", "Clinical ethicist / medico-legal advisor", ("ethics", "consent", "capacity", "best interests", "confidentiality", "withdrawal of treatment"), ("whole body",), "psychosocial"),
              ("chap", "Spiritual-care provider / chaplain", ("spiritual", "faith", "meaning", "bereavement"), ("whole body",), "psychosocial"),
              ("berv", "Bereavement counsellor", ("grief", "bereavement", "loss"), ("brain",), "psychosocial"))),

    # ---------------------------------------------------------------- integrative (evidence-graded)
    U("integ", "Integrative & traditional medicine", ("acupuncture", "herbal", "traditional chinese medicine", "tcm", "ayurveda", "naturopathy", "homeopathy", "yoga", "tai chi", "meditation", "mindfulness", "massage", "supplements", "cannabis", "alternative", "complementary"),
      ("whole body",), ("pharm", "pubh", "nutri"), cat=INT, support=True, facets=(),
      extras=(("acu", "Medical acupuncturist", ("acupuncture", "dry needling", "pain", "nausea"), ("whole body",), "integrative"),
              ("herbal", "Herbal / phytotherapy evidence reviewer", ("herbal", "botanical", "st john's wort", "interaction", "turmeric"), ("whole body",), "integrative"),
              ("tcm", "Traditional Chinese / Ayurvedic medicine practitioner", ("traditional chinese medicine", "tcm", "ayurveda", "qi"), ("whole body",), "integrative"),
              ("mindbody", "Mind-body therapist (yoga, tai chi, mindfulness)", ("yoga", "tai chi", "mindfulness", "meditation", "stress reduction"), ("brain",), "integrative"),
              ("supp", "Supplement & nutraceutical safety reviewer", ("supplement", "nutraceutical", "vitamin", "adulteration", "dose"), ("whole body",), "integrative"))),
]
